version: '3.1'
services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/keys/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./docker/keys/localhost.key:/etc/nginx/certs/localhost.key
    ports:
      - "${NGINX_PORT}:443"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/keys:/etc/nginx/certs
    env_file:
      - .env